# Generated by Django 2.2.5 on 2022-01-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('goal_amount', models.IntegerField(verbose_name='Goal Amount')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('kes', 'KES')], max_length=3, verbose_name='Currency')),
            ],
            options={
                'verbose_name_plural': 'Campaigns',
            },
        ),
    ]
