# Generated by Django 2.2.5 on 2022-01-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_campaign_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('kes', 'KES')], default='usd', max_length=3, verbose_name='Currency'),
        ),
    ]
