# Generated by Django 2.2.5 on 2022-01-23 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0005_auto_20220122_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.MosqueCampaign')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contributions',
                'ordering': ['-amount'],
            },
        ),
        migrations.DeleteModel(
            name='DonationArea',
        ),
    ]
