# Generated by Django 2.2.5 on 2022-01-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_auto_20220123_1150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CampaignTypes',
            new_name='CampaignType',
        ),
    ]
