# Generated by Django 2.2.5 on 2022-01-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_auto_20220123_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MosqueCampaign',
            new_name='DonationItems',
        ),
        migrations.AlterModelOptions(
            name='donationitems',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Donation Items'},
        ),
    ]
