# Generated by Django 2.2.5 on 2022-02-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_auto_20220123_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationitems',
            name='contribution_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contribution Amount'),
        ),
    ]
