# Generated by Django 2.2.5 on 2022-02-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_auto_20220207_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncontribution',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contributions', to='campaign.DonationItems'),
        ),
    ]
