# Generated by Django 2.2.5 on 2022-02-08 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0013_auto_20220207_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncontribution',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
