# Generated by Django 2.2.5 on 2022-02-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0014_auto_20220208_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationitems',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('KES', 'KES')], default='KES', max_length=3, verbose_name='Currency'),
        ),
    ]
