# Generated by Django 2.2.5 on 2022-02-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0015_auto_20220210_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakatNisab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nisab_in_usd', models.FloatField(verbose_name='Nisab in USD')),
                ('nisab_in_kes', models.FloatField(verbose_name='Nisab in Kes')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Zakat Nisab',
                'ordering': ['-updated_on'],
            },
        ),
    ]
