# Generated by Django 2.2.5 on 2022-02-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0016_zakatnisab'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationitems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='zakatnisab',
            name='nisab_in_kes',
            field=models.FloatField(verbose_name='Nisab in KES'),
        ),
    ]
