# Generated by Django 2.2.5 on 2022-04-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0017_auto_20220227_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationitems',
            name='contribution_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Contribution Amount'),
        ),
    ]
