# Generated by Django 2.2.5 on 2022-04-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fajr', models.TimeField(verbose_name='Fajr Time')),
                ('dhuhr', models.TimeField(verbose_name='Dhuhr Time')),
                ('asr', models.TimeField(verbose_name='Asr Time')),
                ('maghrib', models.TimeField(verbose_name='Maghrib Time')),
                ('isha', models.TimeField(verbose_name='Isha Time')),
            ],
            options={
                'verbose_name_plural': 'Paryer Timing',
            },
        ),
    ]
