# Generated by Django 2.2.5 on 2022-04-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paryertiming', '0002_auto_20220414_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayertiming',
            name='asr',
            field=models.TimeField(null=True, verbose_name='Asr Time'),
        ),
        migrations.AddField(
            model_name='prayertiming',
            name='dhuhr',
            field=models.TimeField(null=True, verbose_name='Dhuhr Time'),
        ),
        migrations.AddField(
            model_name='prayertiming',
            name='fajr',
            field=models.TimeField(null=True, verbose_name='Fajr Time'),
        ),
        migrations.AddField(
            model_name='prayertiming',
            name='isha',
            field=models.TimeField(null=True, verbose_name='Isha Time'),
        ),
        migrations.AddField(
            model_name='prayertiming',
            name='maghrib',
            field=models.TimeField(null=True, verbose_name='Maghrib Time'),
        ),
    ]
