# Generated by Django 2.2.5 on 2022-01-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(max_length=280, verbose_name='Summary Message')),
                ('attachment', models.FileField(upload_to='newsletter_uploads', verbose_name='Attachment')),
                ('release_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Mosque News Letters',
                'ordering': ['-release_date'],
            },
        ),
    ]
