# Generated by Django 2.2.5 on 2022-02-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
