# Generated by Django 2.2.5 on 2022-02-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300, verbose_name='Category')),
                ('zekr', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Zekar')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Duas',
            },
        ),
    ]
