# Generated by Django 2.2.5 on 2022-02-14 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuasData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zekr', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Zekar')),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duas.Duas', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'DuasData',
            },
        ),
    ]
