# Generated by Django 2.2.5 on 2022-02-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duas', '0002_duasdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duas',
            name='count',
        ),
        migrations.RemoveField(
            model_name='duas',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='duas',
            name='zekr',
        ),
    ]
