# Generated by Django 2.2.5 on 2022-02-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duas', '0004_auto_20220214_1718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Duas',
            new_name='DuasALL',
        ),
    ]
