# Generated by Django 2.2.5 on 2022-02-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duas', '0005_auto_20220214_1720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DuaCategory',
            new_name='Duas',
        ),
        migrations.RenameModel(
            old_name='DuasALL',
            new_name='DuasData',
        ),
    ]
