# Generated by Django 2.2.5 on 2022-02-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duas', '0007_auto_20220214_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='duacategory',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='duacategory',
            name='zekr',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Zekar'),
        ),
    ]
