# Generated by Django 2.2.5 on 2022-02-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duas', '0008_auto_20220214_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duacategory',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='duacategory',
            name='zekr',
        ),
    ]
